version: '3.7'

services:
  ghost:
    image: ghost:3
    depends_on:
      - db
    ports:
      - 2368:2368
    restart: always
    volumes:
      - ./content:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
    networks:
      - ghostsite

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - ghostsite

  reverse-proxy:
    image: nginx:latest
    restart: always
    environment:
    ports:
      - 80:80
      - 443:443
    volumes: ./nginx:/etc/nginx/
    networks:
      - ghostsite

networks:
  ghostsite:
